### ISSUE TITLE
👌

### ISSUE THREAD

**Issue by zhongwangninja** [wheatwee/MyActions#2]

**Comment by zhongwangninja** [comment]
@wheatwee 不好意思，我的京喜工厂刚黑了。。。联系客服暂时没法解决，明天短期没法继续助力了。你待会删掉我的京喜工厂助力码哈。

**Comment by wheatwee** [comment]
@zhongwangninja 好的，真是不测风云啊！先这样吧，等空了再搞，反正都会自动助力
-------- 原始信息 --------发件人： zhongwangninja <notifications@github.com> 日期: 2020/12/23  13:43  (GMT+08:00) 收件人： wheatwee/MyActions <MyActions@noreply.github.com> 抄送： wheatwee <zhouq312@163.com>, Mention <mention@noreply.github.com> 主题： Re: [wheatwee/MyActions] 👌 (#2) 

@wheatwee 不好意思，我的京喜工厂刚黑了。。。联系客服暂时没法解决，明天短期没法继续助力了。你待会删掉我的京喜工厂助力码哈。



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/wheatwee/MyActions/issues/2#issuecomment-749947562",

"url": "https://github.com/wheatwee/MyActions/issues/2#issuecomment-749947562",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
